version: "3"

services:
 app:
   image: mcr.microsoft.com/dotnet/sdk:6.0
   command: bash -c "dotnet restore && dotnet build && ls && dotnet run --configuration Debug --urls http://+:5000 --project GrafanaTest/GrafanaTest.csproj"
   working_dir: /GrafanaTest
   volumes:
     - ./GrafanaTest:/GrafanaTest
   ports:
     - "5000:5000"
   logging:
    driver: loki
    options:
      loki-url: https://350304:eyJrIjoiMTFmNzM2ZmMxZTdkMDU2NmRmZjQ3YzQ3NjYzODJlNjZiMzMwNGY0YiIsIm4iOiJvdXRyYS1rZXkiLCJpZCI6NzY1MTMxfQ==@logs-prod-015.grafana.net/loki/api/v1/push

 grafana-agent:
   image: grafana/agent:latest
   command: "-config.file=/etc/agent-config.yaml"
   volumes:
     - ./agent-config.yaml:/etc/agent-config.yaml
  